title: Class Projects - Data Culture Group @ Northeastern University
description: Student work that needs a place to live because it has custom code
author: Rahul Bhargava

enableTags: true
tagarray: []

permalink: /:year/:month/:day/:title:output_ext

collections:

social:

share:

urls:

url: "https://class-projects.dataculturegroup.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
